set_property PACKAGE_PIN F16 [get_ports {led[0]}]
set_property PACKAGE_PIN L19 [get_ports {led[1]}]
set_property PACKAGE_PIN M19 [get_ports {led[2]}]
set_property PACKAGE_PIN M17 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property SLEW SLOW [get_ports {led[*]}]
set_property DRIVE 8 [get_ports {led[*]}]
